baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.brainspa.nl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

port: 4000
permalink: pretty

dev: y

exclude: ['CNAME', 'README.md', 'PSD', 'node_modules', 'package.json', 'gruntfile.js']

gems:
- jekyll-redirect-from
- jekyll-sitemap


# prose.io config
prose:
  ignore: ['.gitignore', '_config.yml', 'CNAME', 'gruntfile.js', 'forms.yml', 'package.json', '_includes', '_layouts', 'build']
  siteurl: "http://www.brainspa.nl"
  relativeLinks: 'http://brainspa.publiceervoormij.nl/links.jsonp'
  media: "/assets/img/"
  metadata:
    _posts/workshops:
      - name: "layout"
        field:
          element: "hidden"
          value: "workshop"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Doelgroepen"
          help: "Kies één of meerdere doelgroepen. Kies in ieder workshop."
          placeholder: "kies tag"
          alterable: "true"
          options: 
            - name: workshop
              value: workshop
            - name: voor-jou
              value: voor-jou
            - name: kinderen
              value: kinderen
            - name: zakelijk
              value: zakelijk
      - name: "parent"
        field:
          element: "hidden"
          value: "workshop"
      - name: "class"
        field:
          element: "hidden"
          value: "workshop"
      - name: "noindex"
        field:
          element: "checkbox"
          label: "Voorkom dat google pagina indexeert"
          help: "Als ingeschakeld wordt de pagina niet gevonden in zoekmachines."
          value: false
      - name: "sitemap"
        field:
          element: "checkbox"
          label: "Neem pagina op in sitemap (SEO)"
          value: true
      - name: "publish"
        field:
          element: "checkbox"
          label: "Publiceer op website"
          help: "Schakel uit om pagina niet te tonen in de website."
          value: true
      - name: "published"
        field:
          element: "hidden"
          value: true
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          placeholder: "url van pagina"
          type: "text"
      - name: "redirect_from"
        field:
          element: "multiselect"
          label: "Redirect_from"
          placeholder: "vul url in"
          alterable: "true"
